-- Senior Fitness Test INDER - estructura simplificada y flexible
-- Ejecutar una sola vez en el SQL Editor de Supabase.

create extension if not exists pgcrypto;

create table if not exists public.evaluaciones (
    id uuid primary key default gen_random_uuid(),
    documento text not null,
    nombres text not null,
    fecha_nacimiento date not null,
    sexo text not null check (sexo in ('F','M')),
    edad integer,
    datos jsonb not null default '{}'::jsonb,
    interpretacion jsonb not null default '{}'::jsonb,
    consentimiento boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists evaluaciones_documento_idx
on public.evaluaciones(documento);

create table if not exists public.campos (
    id bigint generated by default as identity primary key,
    clave text unique not null,
    etiqueta text not null,
    grupo text not null default 'Otros',
    tipo text not null default 'texto'
        check (tipo in ('texto','texto_largo','numero','entero','seleccion','checkbox')),
    unidad text,
    opciones jsonb not null default '[]'::jsonb,
    requerido boolean not null default false,
    activo boolean not null default true,
    orden integer not null default 100,
    created_at timestamptz not null default now()
);

create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    accion text not null,
    evaluation_id uuid,
    detalles jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

-- Campos iniciales. Se pueden modificar desde la propia aplicación.
insert into public.campos (clave,etiqueta,grupo,tipo,unidad,requerido,activo,orden,opciones)
values
('comuna','Comuna / corregimiento','Caracterización','texto',null,false,true,10,'[]'),
('profesor','Profesor / formador','Caracterización','texto',null,false,true,20,'[]'),
('codigo_grupo','Código de grupo','Caracterización','texto',null,false,true,30,'[]'),
('patologias','Patologías / condiciones de salud','Salud','texto_largo',null,false,true,40,'[]'),
('medicamentos','Medicamentos, dosis y frecuencia','Salud','texto_largo',null,false,true,50,'[]'),
('peso_kg','Peso','Antropometría','numero','kg',true,true,60,'[]'),
('talla_m','Talla','Antropometría','numero','m',true,true,70,'[]'),
('cintura_cm','Perímetro abdominal / cintura','Antropometría','numero','cm',false,true,80,'[]'),
('pantorrilla_cm','Circunferencia de pantorrilla','Antropometría','numero','cm',false,true,90,'[]'),
('fuerza_prension_kg','Fuerza de prensión','Antropometría','numero','kg',false,true,100,'[]'),
('chair_stand','Sentarse y levantarse en 30 segundos','SFT','entero','repeticiones',true,true,110,'[]'),
('arm_curl','Flexiones del brazo en 30 segundos','SFT','entero','repeticiones',true,true,120,'[]'),
('two_min_step','Marcha de 2 minutos','SFT','entero','pasos',false,true,130,'[]'),
('six_min_walk','Caminata de 6 minutos','SFT','numero','metros',false,true,140,'[]'),
('chair_sit_reach','Sentado y alcanzar el pie','SFT','numero','cm',false,true,150,'[]'),
('back_scratch','Alcanzar manos tras la espalda','SFT','numero','cm',false,true,160,'[]'),
('eight_foot_up_go','Levantarse, caminar y sentarse','SFT','numero','segundos',false,true,170,'[]'),
('observaciones','Observaciones','Cierre','texto_largo',null,false,true,180,'[]')
on conflict (clave) do nothing;

-- Actualizar updated_at automáticamente.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists evaluaciones_set_updated_at on public.evaluaciones;
create trigger evaluaciones_set_updated_at
before update on public.evaluaciones
for each row execute function public.set_updated_at();

-- Esta versión usa la SERVICE ROLE KEY desde un servidor Streamlit.
-- NO ponga esa clave en GitHub; guárdela únicamente como secreto del hosting.
